# Copyright(c) 2012-2018 Intel Corporation
# SPDX-License-Identifier: BSD-3-Clause-Clear

EXTRA_CFLAGS += -I$(M) -I$(I)

EXTRA_CFLAGS += -Werror
EXTRA_CFLAGS += -DIOTRACE_VERSION=$(IOTRACE_VERSION)
EXTRA_CFLAGS += -DIOTRACE_VERSION_LABEL=$(IOTRACE_VERSION_LABEL)
