# Copyright(c) 2012-2018 Intel Corporation
# SPDX-License-Identifier: BSD-3-Clause

include $(M)/config.mk

obj-m := iotrace.o

iotrace-objs = main.o procfs.o io_trace.o trace_bdev.o trace.o trace_bio.o \
	config.o trace_inode.o
